kind: pipeline
#name: default
#steps:
#- name: standalone
 # image: maven:3-jdk-10
 # commands:
 # - cd ./selenium-java-3.141.59/
 # - java -jar selenium-server-standalone.jar
name: starttest
steps:
- name: clean
  image: maven:3-jdk-10
  commands:
  - chmod 777 ./src/Drivers/Chrome/chromedriver
  - mvn clean
#- name: cat
 # image: maven:3-jdk-8
  #commands:
  #- cat /etc/apt/sources.list
#- name: updateAPT
 # image: maven:3-jdk-8
  #commands:
  #- apt-get update
  #- apt-get install -f
- name: downloadChrome
  image: maven:3-jdk-8
  commands:
  - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
#- name: shDownloads
 # image: maven:3-jdk-8
  #commands:
  #- chmod 777 ~/Downloads/crouton
  #- sh -e ~/Downloads/crouton -r saucy -t xfce,chrome -n xfce
- name: installChrome
  image: maven:3-jdk-8
  commands: 
  - apt-get update -y
  - apt-get install -y xdg-utils
  - chmod 777 google-chrome-stable_current_amd64.deb
  - dpkg -i --force-all google-chrome-stable_current_amd64.deb
- name: deleteDownloadedChromeInstaller
  image: maven:3-jdk-8
  commands:
  #- cd ~/
  #- locate chrome
  - cd /usr/
  - find . -maxdepth 1 -name '*chrome*'
  - ls | grep chrome
  #- rm google-chrome-stable_current_amd64.deb
  #- chmod 777 /usr/bin/google-chrome-stable
  #- cd /usr/bin/google-chrome-stable
  #- which google-chrome
  #- google-chrome
- name: test
  image: maven:3-jdk-8
  commands:
  - chmod 777 ./src/Drivers/Chrome/chromedriver
  - mvn -B test
