kind: pipeline
name: default
steps:
- name: clean
  image: maven:3-jdk-10
  commands:
  - mvn clean
  - chmod 777 src/Drivers/Chrome/chromedriver
- name: test
  image: maven:3-jdk-10
  commands:
  - mvn -B test
