kind: pipeline
name: default
steps:
- name: clean
  image: maven:3-jdk-10
  commands:
  - chmod 777 ./src/Drivers/Chrome/chromedriver
  - mvn clean
- name: test
  image: maven:3-jdk-8
  commands:
  - ruby -e "$(curl -fsSL https://raw.github.com/mxcl/homebrew/go/install)"
  - chmod 777 ./src/Drivers/Chrome/chromedriver
  - mvn -B test
