kind: pipeline
name: default
steps:
- name: standalone
  image: maven:3-jdk-10
  commands:
  - cd ./selenium-java-3.141.59/
  - java -jar selenium-server-standalone.jar
- name: clean
  image: maven:3-jdk-10
  commands:
  - chmod 777 ./src/Drivers/Chrome/chromedriver
  - mvn clean
- name: test
  image: maven:3-jdk-8
  commands:
  - chmod 777 ./src/Drivers/Chrome/chromedriver
  - mvn -B test
